# Generated by Django 5.0.7 on 2024-08-02 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_about_display_img_about_education_project_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='education',
        ),
        migrations.RemoveField(
            model_name='about',
            name='social_links',
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.about')),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.URLField()),
                ('about', models.ManyToManyField(to='base.about')),
            ],
        ),
    ]
