# Generated by Django 5.0.7 on 2024-08-02 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_about_education_remove_about_social_links_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='display_img',
            field=models.ImageField(null=True, upload_to='media/user'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.RemoveField(
            model_name='social',
            name='about',
        ),
        migrations.AlterField(
            model_name='social',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='social',
            name='about',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.about'),
        ),
    ]
