# Generated by Django 5.0.7 on 2024-08-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_social_link_alter_about_display_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='social_img',
            field=models.ImageField(null=True, upload_to='media/social'),
        ),
    ]
