# Generated by Django 5.0.7 on 2024-08-02 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_education_education_icon_experience_experience_icon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='skill_icon',
        ),
        migrations.AlterField(
            model_name='skill',
            name='experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill', to='base.experience'),
        ),
    ]
